clone:
  path: github.com/dockhippie/traefik

build:
  prep:
    image: webhippie/golang:latest
    commands:
      - make prep
      - make clone
      - make deps

  node:
    image: webhippie/nodejs:latest
    commands:
      - apk -U add python
      - make node

  build:
    image: webhippie/golang:latest
    commands:
      - make gen
      - make build

cache:
  mount:
    - /drone/src/github.com/containous/traefik/vendor

publish:
  docker:
    username: $$DOCKER_USERNAME
    password: $$DOCKER_PASSWORD
    email: $$DOCKER_EMAIL
    storage_driver: overlay
    repo: webhippie/traefik
    tag: latest
    when:
      repo: dockhippie/traefik
      branch: master

  docker:
    username: $$DOCKER_USERNAME
    password: $$DOCKER_PASSWORD
    email: $$DOCKER_EMAIL
    storage_driver: overlay
    repo: webhippie/traefik
    tag: $$TAG
    when:
      repo: dockhippie/traefik
      event: tag

notify:
  gitter:
    webhook: https://webhooks.gitter.im/e/$$GITTER_TOKEN

  email:
    from: $$EMAIL_FROM
    host: $$EMAIL_HOST
    username: $$EMAIL_USERNAME
    password: $$EMAIL_PASSWORD
    recipients:
      - docker@webhippie.de
